/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julsaint.passgenx;

/**
 *
 * @author rjpro
 */
public class CreateMasterPasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMasterPasswordPanel
     */
    public CreateMasterPasswordPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MasterPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        MasterPasswordField1 = new javax.swing.JPasswordField();
        ConfirmPasswordField1 = new javax.swing.JPasswordField();
        CancelButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setName(""); // NOI18N

        MasterPasswordLabel.setText("Master Password:");

        ConfirmPasswordLabel.setText("Confirm Password:");

        MasterPasswordField1.setColumns(15);
        MasterPasswordField1.setToolTipText("Enter your password");

        ConfirmPasswordField1.setColumns(15);
        ConfirmPasswordField1.setToolTipText("Confirm your password");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MasterPasswordLabel)
                    .addComponent(ConfirmPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubmitButton))
                    .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasterPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasterPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasterPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SubmitButton))
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed

        String MPassword = "";
        String ConfirmMPassword = "";
        char[] MasterPassword = MasterPasswordField1.getPassword();
        char[] ConfirmPassword = ConfirmPasswordField1.getPassword();
        int StatusCode;
        for(char character : MasterPassword){
            MPassword += character;    
        }
        
        for(char character : ConfirmPassword){
            ConfirmMPassword += character;
        }
     
        if(MPassword.equals(ConfirmMPassword)){
            PasswordGeneratorLogin Login = new PasswordGeneratorLogin();
            StatusCode = Login.CreateNewUser(MPassword);
            if(StatusCode == 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Master password created.");
                MainApplicationPanel.UpdatePanelContent(MainApplicationPanel.GetInstance(), new LoginPanel());
            }
            else if(MPassword.length() < 8){
                javax.swing.JOptionPane.showMessageDialog(this, "Master password must be at least 8 characters!");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Master password not created.");
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match!");
        }
        MasterPasswordField1.setText("");
        ConfirmPasswordField1.setText("");
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed

        MainApplicationPanel.UpdatePanelContent(MainApplicationPanel.GetInstance(), new LoginPanel());
    }//GEN-LAST:event_CancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPasswordField ConfirmPasswordField1;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField MasterPasswordField1;
    private javax.swing.JLabel MasterPasswordLabel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
