/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.julsaint.passgenx;

/**
 *
 * @author Ralph Julsaint
 */
public class LoginPanel extends javax.swing.JPanel {
    static boolean IsLoggedIn;//used to track is user is logged in session
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordLabel = new javax.swing.JLabel();
        CreateNewUserButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        PasswordField1 = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 400));

        PasswordLabel.setText("Master Password:");
        PasswordLabel.setToolTipText("");

        CreateNewUserButton.setText("Create");
        CreateNewUserButton.setToolTipText("Create new user account");
        CreateNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewUserButtonActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.setToolTipText("User login button");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        PasswordField1.setColumns(15);
        PasswordField1.setToolTipText("Enter your password");
        PasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateNewUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoginButton)))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewUserButton)
                    .addComponent(LoginButton))
                .addGap(154, 154, 154))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewUserButtonActionPerformed
        MainApplicationPanel.UpdatePanelContent(MainApplicationPanel.GetInstance(), new CreateMasterPasswordPanel());
    }//GEN-LAST:event_CreateNewUserButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String UserPassword = "";
        char[] Password = PasswordField1.getPassword();
        boolean StatusCode;
        for(char character : Password){
            UserPassword += character;    
        }
        PasswordGeneratorLogin Login = new PasswordGeneratorLogin();
        StatusCode = Login.GetUserCredentials(UserPassword);
        if(StatusCode){
            PasswordField1.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Logged in successfully.");
            MainApplicationPanel.UpdatePanelContent(MainApplicationPanel.GetInstance(), new PasswordGenerationPanel());
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Password not found!");
            PasswordField1.setText("");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField1KeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            String UserPassword = "";
            char[] Password = PasswordField1.getPassword();
            boolean StatusCode;
            for(char character : Password){
                UserPassword += character;    
            }
            PasswordGeneratorLogin Login = new PasswordGeneratorLogin();
            StatusCode = Login.GetUserCredentials(UserPassword);
            if(StatusCode){
                PasswordField1.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Logged in successfully.");
                MainApplicationPanel.UpdatePanelContent(MainApplicationPanel.GetInstance(), new PasswordGenerationPanel());
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Password not found!");
                PasswordField1.setText("");
            }
        }
    }//GEN-LAST:event_PasswordField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewUserButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JLabel PasswordLabel;
    // End of variables declaration//GEN-END:variables
}
